=== cairo-caplan/uap/cfg/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Virtual Repository IP list (array of entries)",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["Name", "Category"],
    "properties": {
      "Name": { "type": "string", "minLength": 1 },
      "Category": {
        "oneOf": [
          { "type": "array", "items": { "type": "string" } },
          { "type": "string" }
        ]
      },
      "URL": { "type": "string", "format": "uri" },
      "IP_Card_URL" : { "type": "string", "format": "uri" },
      "Project": { "type": "string" },
      "WI": {
        "oneOf": [
          { "type": "array", "items": { "type": "string" } },
          { "type": "string" }
        ]
      },
      "Partners": {
        "oneOf": [
          { "type": "array", "items": { "type": "string" } },
          { "type": "string" }
        ]
      },
      "Status": { "type": "string" },
      "Description": { "type": "string" },
      "License": {
         "oneOf": [
          { "type": "array", "items": { "type": "string" } },
          { "type": "string" }
        ]
      },
      "Comment": { "type": "string" }
    },
    "additionalProperties": true
  }
}

=== cairo-caplan/uap/ips/isolde.json
[
  {
    "Project": "ISOLDE",
    "Name": "NOEL-V processor extensions",
    "URL": "",
    "License": "GPL",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.1.01"
    ],
    "Partners": "GSL",
    "Comment": "GPL",
    "Category": "Cores, interfaces, peripherals & NoCs"
  },
  {
    "Project": "ISOLDE",
    "Name": "CVA6 processor extensions",
    "URL": "",
    "License": "Solderpad",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.1.02"
    ],
    "Partners": "TDIS",
    "Comment": "Solderpad",
    "Category": "Cores, interfaces, peripherals & NoCs"
  },
  {
    "Project": "ISOLDE",
    "Name": "CV32E40X processor extensions",
    "URL": "",
    "License": "MIT",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.1.03"
    ],
    "Partners": "HM",
    "Comment": "MIT",
    "Category": "Cores, interfaces, peripherals & NoCs"
  },
  {
    "Project": "ISOLDE",
    "Name": "Testing Design Parameters for CVA6",
    "URL": "",
    "License": "Open Source",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.1.04"
    ],
    "Partners": "UZL",
    "Comment": "Open Source",
    "Category": "Cores, interfaces, peripherals & NoCs"
  },
  {
    "Project": "ISOLDE",
    "Name": "Analysis Framework",
    "URL": "",
    "License": "Proprietary",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.1.05"
    ],
    "Partners": "IFX",
    "Comment": "Proprietary",
    "Category": "Cores, interfaces, peripherals & NoCs"
  },
  {
    "Project": "ISOLDE",
    "Name": "Context-Aware Bus",
    "URL": "",
    "License": "Solderpad",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.2.01"
    ],
    "Partners": "TRT",
    "Comment": "Solderpad",
    "Category": "Cores, interfaces, peripherals & NoCs"
  },
  {
    "Project": "ISOLDE",
    "Name": "Wormhole NoC",
    "URL": "https://gitlab.com/selene-riscv-platform/euros2pronoc/-/tree/AXI-MM-Network-Interface?ref_type=heads",
    "License": "MIT",
    "Status": "Completed, tested",
    "Description": "Tile-oriented SoC design, where components located at different tiles exchange messages in a unified manner. IPs will interface to the NoC by means of a Network Interface (NI) which complies with AXI protocol. The NoC router supports 2D mesh topologies.",
    "WI": [
      "ID 2.2.02"
    ],
    "Partners": "UPV",
    "Comment": "MIT",
    "Category": "Cores, interfaces, peripherals & NoCs"
  },
  {
    "Project": "ISOLDE",
    "Name": "AXI Sniffer",
    "URL": "https://gitlab.com/selene-riscv-platform/selene-hardware/-/tree/master/interconnect/libnoc/mem_monitor",
    "License": "MIT",
    "Status": "Completed, verified",
    "Description": "Monitors the network activity in AXI interconnects. Tracks the timing contention between the different traffic sources on an AXI network for each given destination.",
    "WI": [
      "ID 2.2.03"
    ],
    "Partners": "UPV",
    "Comment": "MIT",
    "Category": "Cores, interfaces, peripherals & NoCs"
  },
  {
    "Project": "ISOLDE",
    "Name": "AHB Crossbar",
    "URL": "",
    "License": "TBD",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.2.04"
    ],
    "Partners": "IFX",
    "Comment": "TBD",
    "Category": "Cores, interfaces, peripherals & NoCs"
  },
  {
    "Project": "ISOLDE",
    "Name": "AHB/APB Interrupt Controller",
    "URL": "",
    "License": "TBD",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.2.05"
    ],
    "Partners": "IFX",
    "Comment": "TBD",
    "Category": "Cores, interfaces, peripherals & NoCs"
  },
  {
    "Project": "ISOLDE",
    "Name": "AHB/APB Timer",
    "URL": "",
    "License": "TBD",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.2.06"
    ],
    "Partners": "IFX",
    "Comment": "TBD",
    "Category": "Cores, interfaces, peripherals & NoCs"
  },
  {
    "Project": "ISOLDE",
    "Name": "GRLIB IP library",
    "URL": "https://www.gaisler.com/getgrlib",
    "License": "GPL",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.2.07"
    ],
    "Partners": "GSL",
    "Comment": "GPL",
    "Category": "Cores, interfaces, peripherals & NoCs"
  },
  {
    "Project": "ISOLDE",
    "Name": "Hypervisor virtualization support to low-cost HW IPs",
    "URL": "",
    "License": "Proprietary",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.2.08"
    ],
    "Partners": "FENTISS",
    "Comment": "Proprietary",
    "Category": "Cores, interfaces, peripherals & NoCs"
  },
  {
    "Project": "ISOLDE",
    "Name": "Context-Aware CORE Extensions",
    "URL": "",
    "License": "Solderpad",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.3.01"
    ],
    "Partners": "TRT",
    "Comment": "Solderpad",
    "Category": "Cores, interfaces, peripherals & NoCs"
  },
  {
    "Project": "ISOLDE",
    "Name": "Memory bank interface",
    "URL": "https://bitbucket.org/fnpub/isolde/",
    "License": "Open Source",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.3.02"
    ],
    "Partners": "FotoNation",
    "Comment": "Open Source",
    "Category": "Cores, interfaces, peripherals & NoCs"
  },
  {
    "Project": "ISOLDE",
    "Name": "Extension interface for NOEL-V",
    "URL": "",
    "License": "GPL",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.3.03"
    ],
    "Partners": "GSL",
    "Comment": "GPL",
    "Category": "Cores, interfaces, peripherals & NoCs"
  },
  {
    "Project": "ISOLDE",
    "Name": "Extension interface for CVA6",
    "URL": "",
    "License": "Solderpad",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.3.04"
    ],
    "Partners": "TDIS",
    "Comment": "Solderpad",
    "Category": "Cores, interfaces, peripherals & NoCs"
  },
  {
    "Project": "ISOLDE",
    "Name": "Interface between CVA6 and Vector accelerator",
    "URL": "https://github.com/pulp-platform/ara (branch: mp/xif , commit: f06204b )",
    "License": "Solderpad",
    "Status": "Prototype. To be updated with the final release of CV-X-IF in CVA6",
    "Description": "Prototype of CV-X-IF between CVA6 and RVV 1.0 vector processor, used for evaluation",
    "WI": [
      "ID 2.3.05"
    ],
    "Partners": "ETHZ",
    "Comment": "Solderpad",
    "Category": "Cores, interfaces, peripherals & NoCs"
  },
  {
    "Project": "ISOLDE",
    "Name": "XNG NOEL-V BSP update to RISC-V new specifications",
    "URL": "",
    "License": "Proprietary",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.4.01"
    ],
    "Partners": "FENTISS",
    "Comment": "Proprietary",
    "Category": "Cores, interfaces, peripherals & NoCs"
  },
  {
    "Project": "ISOLDE",
    "Name": "CVA6 multicore experiments and analysis",
    "URL": "",
    "License": "TBD",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.4.02"
    ],
    "Partners": "SYSGO",
    "Comment": "TBD",
    "Category": "Cores, interfaces, peripherals & NoCs"
  },
  {
    "Project": "ISOLDE",
    "Name": "SW Abstraction Layer for RISC-V Processors",
    "URL": "",
    "License": "Proprietary",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.4.03"
    ],
    "Partners": "IFX",
    "Comment": "Proprietary",
    "Category": "Cores, interfaces, peripherals & NoCs"
  },
  {
    "Project": "ISOLDE",
    "Name": "NOEL-V software tools",
    "URL": "",
    "License": "GPL",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 2.4.04"
    ],
    "Partners": "GSL",
    "Comment": "GPL",
    "Category": "Cores, interfaces, peripherals & NoCs"
  },
  {
    "Project": "ISOLDE",
    "Name": "Safety-related Traffic Injector",
    "URL": "https://github.com/bsc-loca/SafeTI/",
    "License": "MIT",
    "Status": "Released",
    "Description": "Programmable traffic innjector that can be used for platform co-testing and offers a large variety of applications",
    "WI": [
      "ID 3.1.01"
    ],
    "Partners": "BSC",
    "Comment": "MIT",
    "Category": "Accelerators and extensions"
  },
  {
    "Project": "ISOLDE",
    "Name": "IPs with integrated Context-Aware PMCs",
    "URL": "",
    "License": "TBD",
    "Status": "",
    "Description": "TBD",
    "WI": [
      "ID 3.1.02"
    ],
    "Partners": "TRT",
    "Comment": "TBD",
    "Category": "Accelerators and extensions"
  },
  {
    "Project": "ISOLDE",
    "Name": "Inline Encryption Engine",
    "URL": "",
    "License": "Proprietary",
    "Status": "Verified",
    "Description": "Provides low-latency tweakable memory encryption for mitigating logical and selected physical attacks.",
    "WI": [
      "ID 3.1.01"
    ],
    "Partners": "NXP-AT",
    "Comment": "",
    "Category": "Accelerator, Extension"
  },
  {
    "Project": "ISOLDE",
    "Name": "Backward-Edge Control Flow Integrity Unit",
    "URL": "",
    "License": "Proprietary",
    "Status": "Verified",
    "Description": "Ensures backward-edge control flow integrity by detecting tampering with return addresses under logical and selected physical attacks.",
    "WI": [
      "ID 3.1.02"
    ],
    "Partners": "NXP-AT",
    "Comment": "",
    "Category": "Extension"
  },
  {
    "Project": "ISOLDE",
    "Name": "Cryptographically Tagged Memory Unit",
    "URL": "",
    "License": "Proprietary",
    "Status": "Verified",
    "Description": "Enforces memory safety by tagging memory objects and their associated pointers, mitigating logical and selected physical attacks.",
    "WI": [
      "ID 3.1.03"
    ],
    "Partners": "NXP-AT",
    "Comment": "",
    "Category": "Extension"
  },
  {
    "Project": "ISOLDE",
    "Name": "Enclave Memory Isolation Unit",
    "URL": "",
    "License": "Proprietary",
    "Status": "Verified",
    "Description": "Enables cryptographic isolation of sensitive workloads in memory, mitigating logical and selected physical attacks.",
    "WI": [
      "ID 3.1.04"
    ],
    "Partners": "NXP-AT",
    "Comment": "",
